title: Mochiling
email: xavijam@gmail.com
baseurl: ""
url: "http://mochiling.es"
languages: ["es", "en"]
exclude_from_localizations: ["img", "_assets"]
markdown: kramdown
gems: [jekyll-admin, jekyll-multiple-languages-plugin]