title: Mochiling
email: mochiling.es@gmail.com
baseurl: ""
keywords: "mochiling,backpack,backpacking,aventura,viaje diferente,mochileo,explorar"
url: "http://mochiling.es"
languages: ["es", "en"]
exclude_from_localizations: ["img", "_assets"]
markdown: kramdown
gems: [jekyll-admin, jekyll-multiple-languages-plugin]

instagramConfig:
  clientId: "8edddd77898d4100bfac8f4b58e54c25"
  accessToken: "9841730.ba4c844.3ce456308101453787eb5443d358c259"

social:
  facebook: https://www.facebook.com/mochiling.es/
  instagram: https://www.instagram.com/mochiling.es/
  twitter: https://twitter.com/mochilinges

google:
  site-verification: O_SdK5E1cltoBvX_c5Ibpw_qtwIkR-Kq1JgYQZdC2RM